export enum Icons {
  none = 0,
  man,
  woman,
  elderly,
  person_play,
  sports_gymnastics,
  shield_person,
  mediation,
  swords,
  science,
  psychology,
  skull,
  raven,
  flare,
  local_fire_department,
  water_drop,
  bolt,
  precision_manufacturing,
  smart_toy,
  front_loader,
  park,
  pest_control,
  eda,
  diversity_2,
}

export const ICONS_LOCALIZATION: Record<Icons, string> = {
  [Icons.none]: "Нет",
  [Icons.man]: "Мужчина",
  [Icons.woman]: "Женщина",
  [Icons.elderly]: "Старик",
  [Icons.person_play]: "Волшебник",
  [Icons.sports_gymnastics]: "Боец",
  [Icons.shield_person]: "Щит",
  [Icons.mediation]: "Лук",
  [Icons.swords]: "Мечи",
  [Icons.science]: "Алхимик",
  [Icons.psychology]: "Головной процесс",
  [Icons.skull]: "Враг",
  [Icons.raven]: "Ворон",
  [Icons.flare]: "Свет",
  [Icons.local_fire_department]: "Огонь",
  [Icons.water_drop]: "Вода",
  [Icons.bolt]: "Молния",
  [Icons.precision_manufacturing]: "Механизм",
  [Icons.smart_toy]: "Конструкт",
  [Icons.front_loader]: "Техника",
  [Icons.park]: "Природа",
  [Icons.pest_control]: "Насекомое",
  [Icons.eda]: "Кулак",
  [Icons.diversity_2]: "Магия"
}
